### ISSUE TITLE
Fatal error in bobbingwidetechsupport.com

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#146]
Fatal error: Uncaught Error: Call to undefined function oik\oik_blocks\oik_blocks_register_editor_scripts() in /home/bobbingw/public_html/wp-content/plugins/oik/oik.php:550 Stack trace: #0 /home/bobbingw/public_html/wp-includes/class-wp-hook.php(287): oik_register_dynamic_blocks('') #1 /home/bobbingw/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/bobbingw/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/bobbingw/public_html/wp-settings.php(540): do_action('init') #4 /home/bobbingw/public_html/wp-config.php(95): require_once('/home/bobbingw/...') #5 /home/bobbingw/public_html/wp-load.php(37): require_once('/home/bobbingw/...') #6 /home/bobbingw/public_html/wp-blog-header.php(13): require_once('/home/bobbingw/...') #7 /home/bobbingw/public_html/index.php(17): require('/home/bobbingw/...') #8 {main} thrown in /home/bobbingw/public_html/wp-content/plugins/oik/oik.php on line 550

**Comment by bobbingwide** [comment]
The problem was due to an out of date version of oik-lib ( oik library management ) being activated. 0.0.7.  Updating it to v0.1.0 cleared the problem and allowed oik, oik-css and uk-tides to load their blocks.
