### ISSUE TITLE
Uncaught Error Call to undefined method BW_::e 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#164]
I got this error viewing `https://www.oik-plugins.com/oik_shortcodes/bw_directions-2/`
Problem happens in the local development environment too.

Fatal error: Uncaught Error: Call to undefined method BW_::e() in /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/shortcodes/oik-geo.php:67 Stack trace: #0 /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/libs/oik-sc-help.php(159): bw_directions__example('bw_directions', NULL) #1 /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/libs/bobbfunc.php(919): bw_lazy_sc_example('bw_directions', NULL) #2 /home/customer/www/oik-plugins.com/public_html/wp-includes/class-wp-hook.php(287): bw_sc_example('bw_directions') #3 /home/customer/www/oik-plugins.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/customer/www/oik-plugins.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/shortcodes/oik-codes.php(301): do_action('bw_sc_example', 'bw_directions') #6 /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/libs/oik-short in /home/customer/www/oik-plugins.com/public_html/wp-content/plugins/oik/shortcodes/oik-geo.php on line 67

**Comment by bobbingwide** [comment]
### Explanation
There isn't an `e()` method in  class `BW_`. 

### Proposed solution
Use either `e()` or `BW_::p()`.
