### ISSUE TITLE
Extract plugin and theme update logic into shared libraries

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#55]
There are a couple of premium plugins which are available from oik-plugins.com but are not able to detect updates. They have no dependency on the oik base plugin and it doesn't seem wise to require customers to install the oik base plugin just to check for updates. 
Although the allow-reinstalls plugin can be used if a plugin does need to be updated it would be better if the premium plugin included the update checking logic. 
### Proposed solution

for the oik-weight-zone-shipping-pro plugin we'll extract the relevant logic into shared libraries. The oik logic will not be loaded for the front-end. It will only load the libraries when required. Some of the logic in oik will have to be changed - switching from oik_require() to oik_require_lib() and perhaps to cater for the fact that the logic may be shared by other plugins and themes. 

See also https://github.com/bobbingwide/oik-weight-zone-shipping-pro/issues/4 
Note: this is a private repo.

**Comment by bobbingwide** [comment]
Some of the functions used by the oik_plugins and oik_themes routines are not available from shared libraries. When correcting this we will have to allow for there being incompatible versions. 

- The fallback library loading logic in the new code will have to check the version of the currently loaded libraries to ensure they are compatible with the required versions. 
- If there are incompatibilities then the code needs to fail gracefully
- Version numbers in each library file that will need changing will be increased. 
- We need to change the minor version numbers.
- Also, in a couple of libraries the constant that is checked for needs to be changed from LIBRARY_NAME_LOADED to LIBRARY_NAME_INCLUDED

Library |  Current version | Required version
------- | ----------------- | -----------------
bobbfunc | 3.0.0 | 3.1.0
bobbforms | 2.6, 3.0.1 | 3.1.0
oik_boot | 3.0.0 | 3.1.0 
oik_depends | 2.6 | 2.7.0
oik_update | n/a | 


To resolve the problem the user will have to update the plugins that are delivering back level libraries: oik, oik-bwtrace, etc

**Comment by bobbingwide** [comment]
### Preventing backward incompatible changes

When a function that was not previously shared is copied then we need to protect against errors due to the function being redefined. Version checking against shared libraries lets us prevent the new code from redefining existing functions, but it doesn't protect us against the original code that isn't aware that the function has been copied. 

We need a strategy that will support the migration of logic from non-shared to shared without breaking any sites. 

Here are a number of approaches:

1. Protect against loading files that contain duplicate function names.
2. Rename the function in the shared library.
3. Implement functions as static methods.
4. Use PHP namespaces.

The first option is probably the hardest.  Wrapping shared library functions in `!defined( library_name_INCLUDED )` tests and wrapping functions in `!function_exists( duplicated_function )` tests does not protect against the back level logic which is not aware of the problem.
While the cloned code may remain unchanged, the shared library logic will have to ensure that it attempts to do its stuff after the back level code has done its stuff.

e.g. original code: original.php
```
function f1() {} 
```

library file: lib1.php
``` 
if ( !defined( 'LIB1_INCLUDED' ) ) {
  define( 'LIB1_INCLUDED', 'x.y.z' );
  if ( !function_exists( "f1" ) ) { 
    function f1() {}
  } 
}
```
If `lib1.php` is loaded after `original.php` then that's OK. 
The other way round we get.

Fatal error: Cannot redeclare f1() (previously declared in lib1.php:5) in original.php on line 2

Renaming the function seems to be the easiest technically. It provides a clear update path. The original function can be deprecated and eventually removed. Choosing the best name for the new function could be tricky. 

Using static class methods and / or PHP namespaces is another way of renaming the function.
```
class Lib1_class {
static function f1() {}
}
```



Using PHP namespaces in WordPress code has been a problem historically since WordPress is still supported on PHP 5.2 and namespaces were introduced in PHP 5.3. In order to use namespaces we'd have to check the PHP version before attempting to load files that used them. 
This isn't actually too problematic.  We can probably use importing and aliasing to reduce the number of code changes that will be required. http://php.net/manual/en/language.namespaces.importing.php

**Comment by bobbingwide** [comment]
### Preventing Fatal errors in PHP 5.2
Is this a problem? I'm still not sure about using namespaces in the oik base plugin. If I wanted to develop and test code that dies gracefully under PHP 5.2 I'd need to still have it installed. But where would I put the logic that protects against the errors that occur when using the namespace keyword? Just before the first attempt to load the shared library logic I suppose. Is this worth doing when I already have a solution using static methods. Answer... it's probably Yes.

**Comment by bobbingwide** [comment]
Functions which are needed by shared library code and which need to be implemented as static methods to avoid the backward compatibility problems are:

Function | Implement in | Not in!
--------- | --------------- | ------------
bw_get_option | class-bobbcomp.php | bobbfunc.php
bw_array_get_dcb | class-bobbcomp.php | bobbfunc.php

**Comment by bobbingwide** [comment]
It would be nice if, for plugins or themes that are registered programmatically then the Delete action is not available. Currently, if you click on the action it appears to do nothing.

**Comment by bobbingwide** [comment]
It would also be nice if the expiration column were removed from the table. It's not used.

**Comment by bobbingwide** [comment]
One of the challenges of supporting backward compatibility is testing. Even though the 'new' code was released as part of oik-weight-zone-shipping-pro v0.1.0 I'm still finding problems with plugins that are using functions that should have been deprecated. Sometimes the Fatal errors are 'valid' and other times they're spurious... like this one

```
<b>Fatal error</b>:  Uncaught Error: Class 'bobbcomp' not found in C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\oik-admin.php:29
Stack trace:
#0 C:\apache\htdocs\wordpress\wp-content\plugins\oik\admin\oik-admin.inc(32): bw_load_plugin('bw_buttons', 'oik-paypal-shor...')
#1 C:\apache\htdocs\wordpress\wp-content\plugins\oik\oik.php(204): oik_options_init()
#2 C:\apache\htdocs\hm\wp-includes\plugin.php(525): oik_admin_init('')
#3 C:\apache\htdocs\hm\wp-admin\admin.php(168): do_action('admin_init')
#4 C:\apache\htdocs\hm\wp-admin\post.php(12): require_once('C:\\apache\\htdoc...')
#5 {main}
```

**Comment by bobbingwide** [comment]
I think it’s safe to close this now. In the latest version of oik-bwtrace there’s logic that tries to ensure the commonly used functions are loaded if they haven’t been loaded already. I used similar logic in the new version of oik-css. oik-css now supports a CSS block ( oik-css/css ) and a GeSHi block ( oik-css/geshi) . The new logic used shared libraries, so the plugin is only dependent upon oik for the shortcodes.
