### ISSUE TITLE
Fatal error: class 'bobbcomp' not found in WPMS Network Admin interface

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#60]
With oik v3.1.0 the following message is being displayed when using WordPress Multisite and visiting the Network Admin interface. 

```
Fatal error: Class ‘bobbcomp’ not found in 
/home/rlfcon5/public_html/wp-content/plugins/oik/libs/oik-admin.php on line 29
```

**Comment by bobbingwide** [comment]
I've reproduced the error on an install running WordPress 4.6, visiting wp-admin/network


<b>Fatal error</b>:  Uncaught Error: Class 'bobbcomp' not found in /home/oikeu/public_html/wp-content/plugins/oik/libs/oik-admin.php:29
Stack trace:
```
#0 /home/oikeu/public_html/wp-content/plugins/oik/admin/oik-admin.inc(32): bw_load_plugin('bw_buttons', 'oik-paypal-shor...')
#1 /home/oikeu/public_html/wp-content/plugins/oik/oik.php(204): oik_options_init()
#2 /home/oikeu/public_html/wp-includes/plugin.php(524): oik_admin_init('')
#3 /home/oikeu/public_html/wp-admin/admin.php(154): do_action('admin_init')
#4 /home/oikeu/public_html/wp-admin/network/admin.php(13): require_once('/home/oikeu/pub...')
#5 /home/oikeu/public_html/wp-admin/network/index.php(11): require_once('/home/oikeu/pub...')
#6 {main}
  thrown in <b>/home/oikeu/public_html/wp-content/plugins/oik/libs/oik-admin.php</b> on line <b>29</b><br />
```
