### ISSUE TITLE
Fatal error: Call to undefined function bw_sc_link() in includes/oik-sc-help.inc:158

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#87]
When testing the `bw_code__example` function the expected link to the oik shortcode didn't match the actual. On oik-plugins.com, I attempted to determine the current value and got this Fatal error.

```
Uncaught Error: Call to undefined function bw_sc_link() in /oik/includes/oik-sc-help.inc:158 
Stack trace: 
#0 oik/includes/oik-sc-help.inc(643): bw_lazy_sc_syntax('oik') 
#1 oik/includes/oik-sc-help.inc(134): bw_code__example('bw_code', NULL)
#2 oik-bwtrace/libs/bobbfunc.php(905): bw_lazy_sc_example('bw_code', NULL) 
#3 wp-includes/class-wp-hook.php(298): bw_sc_example('bw_code') 
#4 wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) 
#5 wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#6 oik/admin/oik-admin.inc(797): do_action('bw_sc_example', 'bw_code') 
#7 oik/libs/oik-admin.php(61): oik_code_example() 
#8 oik/includes/oik-sc-help.inc on line 158
```

**Comment by bobbingwide** [comment]
The code no longer produces an error but the example and snippet for bw_code a bit confusing. Perhaps this should be improved.
